export const typePlacesList = {
  establishment: 'Establecimiento',
  restaurant: 'Restaurante',
  lodging: 'Alojamiento',
  shopping_mall: 'Centro comercial',
  gym: 'Gimnasio',
  primary_school: 'Escuela primaria',
  secondary_school: 'Escuela secundaria',
  finance: 'Finanzas',
  post_office: 'Oficina de correos',
  place_of_worship: 'Lugar de culto',
  bus_station: 'Estación de autobús',
  train_station: 'Estación de tren',
  subway_station: 'Estación de metro',
  transit_station: 'Estación de tránsito',
  light_rail_station: 'Estación de tren ligero',
  church: 'Iglesia',
  museum: 'Museo',
  university: 'Universidad',
  park: 'Parque',
  airport: 'Aeropuerto',
  hospital: 'Hospital',
  supermarket: 'Supermercado',
  library: 'Biblioteca',
  car_wash: 'Lavado de autos',
  car_repair: 'Reparación de autos',
  movie_theater: 'Cine',
  bank: 'Banco',
  pharmacy: 'Farmacia',
  school: 'Escuela',
  book_store: 'Librería',
  department_store: 'Grandes almacenes',
  bar: 'Bar',
  doctor: 'Doctor',
  city_hall: 'Ayuntamiento',
  local_government_office: 'Oficina de gobierno local',
  atm: 'Cajero automático',
  hardware_store: 'Tienda de hardware',
  amusement_park: 'Parque de diversiones',
  aquarium: 'Acuario',
  art_gallery: 'Galería de arte',
  bicycle_store: 'Tienda de bicicletas',
  bowling_alley: 'Bolera',
  cafe: 'Cafetería',
  campground: 'Campamento',
  car_rental: 'Alquiler de autos',
  cemetery: 'Cementerio',
  clothing_store: 'Tienda de ropa',
  convenience_store: 'Tienda de conveniencia',
  courthouse: 'Tribunal',
  dentist: 'Dentista',
  electrician: 'Electricista',
  electronics_store: 'Tienda de electrónica',
  embassy: 'Embajada',
  florist: 'Florería',
  funeral_home: 'Funeraria',
  general_contractor: 'Contratista general',
  hindu_temple: 'Templo hindú',
  jewelry_store: 'Joyería',
  laundry: 'Lavandería',
  liquor_store: 'Licorería',
  locksmith: 'Cerrajería',
  meal_delivery: 'Entrega de comida',
  mosque: 'Mezquita',
  movie_rental: 'Alquiler de películas',
  painter: 'Pintor',
  pet_store: 'Tienda de mascotas',
  physiotherapist: 'Fisioterapeuta',
  plumber: 'Fontanero',
  police: 'Policía',
  roofing_contractor: 'Contratista de techos',
  rv_park: 'Parque de autocaravanas',
  taxi_stand: 'Parada de taxis',
  veterinary_care: 'Atención veterinaria',
  zoo: 'Zoológico',
  tourist_attraction: 'Atracción turística',
};
