export const typePlacesList = {
  establishment: 'Establishment',
  restaurant: 'Restaurant',
  lodging: 'Lodging',
  shopping_mall: 'Shopping Mall',
  gym: 'Gym',
  primary_school: 'Primary School',
  secondary_school: 'Secondary School',
  finance: 'Finance',
  post_office: 'Post Office',
  place_of_worship: 'Place of Worship',
  bus_station: 'Bus Station',
  train_station: 'Train Station',
  subway_station: 'Subway Station',
  transit_station: 'Transit Station',
  light_rail_station: 'Light Rail Station',
  church: 'Church',
  museum: 'Museum',
  university: 'University',
  park: 'Park',
  airport: 'Airport',
  hospital: 'Hospital',
  supermarket: 'Supermarket',
  library: 'Library',
  car_wash: 'Car Wash',
  car_repair: 'Car Repair',
  movie_theater: 'Movie Theater',
  bank: 'Bank',
  pharmacy: 'Pharmacy',
  school: 'School',
  book_store: 'Book Store',
  department_store: 'Department Store',
  bar: 'Bar',
  doctor: 'Doctor',
  city_hall: 'City Hall',
  local_government_office: 'Local Government Office',
  atm: 'ATM',
  hardware_store: 'Hardware Store',
  amusement_park: 'Amusement Park',
  aquarium: 'Aquarium',
  art_gallery: 'Art Gallery',
  bicycle_store: 'Bicycle Store',
  bowling_alley: 'Bowling Alley',
  cafe: 'Cafe',
  campground: 'Campground',
  car_rental: 'Car Rental',
  cemetery: 'Cemetery',
  clothing_store: 'Clothing Store',
  convenience_store: 'Convenience Store',
  courthouse: 'Courthouse',
  dentist: 'Dentist',
  electrician: 'Electrician',
  electronics_store: 'Electronics Store',
  embassy: 'Embassy',
  florist: 'Florist',
  funeral_home: 'Funeral Home',
  general_contractor: 'General Contractor',
  hindu_temple: 'Hindu Temple',
  jewelry_store: 'Jewelry Store',
  laundry: 'Laundry',
  liquor_store: 'Liquor Store',
  locksmith: 'Locksmith',
  meal_delivery: 'Meal Delivery',
  mosque: 'Mosque',
  movie_rental: 'Movie Rental',
  painter: 'Painter',
  pet_store: 'Pet Store',
  physiotherapist: 'Physiotherapist',
  plumber: 'Plumber',
  police: 'Police',
  roofing_contractor: 'Roofing Contractor',
  rv_park: 'RV Park',
  taxi_stand: 'Taxi Stand',
  veterinary_care: 'Veterinary Care',
  zoo: 'Zoo',
  tourist_attraction: 'Tourist Attraction',
};
